eureka:
  client:
    service-url:
      # 指定eureka服务器的地址
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    # 指定进行服务注册时该服务的名称
    name: order
  datasource:
    url: jdbc:mysql://118.126.111.144:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8085

PRODUCT: # 应用名称
  ribbon:
   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule